name: Autobuild
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run build script
      run: sudo apt-get -y install tree && chmod +x ./build.sh && ./build.sh 
